### ISSUE TITLE
Add upload scalastyle report capability

### ISSUE THREAD

**Issue by NoamShaish** [mwz/sonar-scala#137]
Hi,
In order to enable developers a quick feedback loop I would like to have the build report any scalastyle issues (using scalastayle maven plugin for example) but after error were fixed there still stay some warnings and infos that I would like to expose in sonar.
Currently I would have to duplicate my scalastyle configuration into a sonar quality profile gate, instead of just uploading the resulted report.
I would basically like the same behaviour as the scapegoat have. something like: 
`sonar.scala.scalastyle.reportPath` property

**Comment by mwz** [comment]
Hi @NoamShaish. It's something that we've talked about a few times and while it's easier to manage your scalastyle config locally for one project, my opinion on this is that the real benefits of sonar are in having a centralised quality profile which applies across all of your projects and it's much more difficult to standardise and maintain a consistent style configuration across many projects if the config doesn't come from a single place (even if you extracted this into a shared dependency, there is still a bit of effort involved in keeping your projects in sync). Setting up your own quality profile is easy and doesn't take much effort and once you've done that, there is almost no maintenance effort involved in keeping your rules consistent across all of your projects. We already provide multiple built-in quality profiles which you can use as your base and inherit from or duplicate and customise them according to your needs.

Another thing which I need to mention (since you referred to scapegoat) is that the scapegoat report is used only to match the issues found in your projects with rules from your active quality profile, so e.g. overriding rule levels locally won't be reflected in sonar since the remote rules are configured to override your local configuration - we try to be consistent on this for both scalastyle and scapegoat. The only reason we need a scapegoat report in the first place is because we cannot run the analysis at runtime, like we do it with scalastyle - otherwise we would have done it in the same way.

I might be wrong on this and feel free to correct me, but any inline issues which aren't created against any quality profile cannot be aggregated and linked across multiple projects, so by doing that and blindly populating the report into sonar you would be losing a bigger picture (including the ability to find which issues are occurring the most across all of your projects).

Regarding a quicker feedback loop, I personally find the PR annotation to be good enough and no longer have the need to run scalastyle or scapegoat locally because I rely on sonar to automatically tell me about any issues in the comments when my PR checks are run on every commit.

Does that change your opinion or are you still convinced that uploading reports is a good idea?

**Comment by NoamShaish** [comment]
Hi @mwz , thank you for your replay.
I see your point regarding multiple project profile management and it is probably the right approach, but than I would consider a way to build a profile from an existing scalastyle configuration file to make adoption of this approach easier.

One thing which I am not sure about is the feedback loop, PR means a developer already pushed to repository meaning the code pushed to repo is potentially in lower quality. 
Most IDE's (In my case Intellij) have integration to scalastyle config file so a developer can get the feedback directly while developing, in addition I can use maven plugin to file the build if style was violated (hoping developers will at least try to build the code once before pushing it).

Regarding scapegoat, my approach is again I prefer failing a build by setting the compiler -Xfatal-warning so scapegoat will fail builds even on warnings. In case of sonar I would have a different profile a bit less strict that will just produce the report.

Mainly I would like to use Sonar as visualisation layer for the project quality and enforce as much as possible at developer side (IDE, build etc.) so my repo will be in high quality at all time (keep the "shit" out)
