### ISSUE TITLE
Missing measures for custom metrics

### ISSUE THREAD

**Issue by wei-luo-exa** [mwz/sonar-scala#432]
Only sonar-scala-lts project on https://sonar.sonar-scala.com/projects has statement coverage, all other scala projects don't.

**Comment by mwz** [comment]
It seems that custom metrics are now deprecated and are supposedly getting removed in the future.

![Screenshot 2020-04-26 at 19 20 39](https://user-images.githubusercontent.com/1190768/80316243-7c930000-87f4-11ea-8a6a-f121bc0826f4.png)

It is quite confusing from the plugin perspective because they are not deprecated in the API, so I'd expect to still see the measures in the activity graph, but it doesn't seem to be the case any more. There is no warning when the plugin creates those metrics and saves any measures for them.

I've opened a new thread about this on their forum to get this clarified. You can follow it here https://community.sonarsource.com/t/deprecation-of-custom-metrics/23690.

**Comment by wei-luo-exa** [comment]
Thanks Michael for taking care of this. Since the custom metrics is very important for us, can I continue to use old release 7.4? Is there docker image for 7.4?

**Comment by mwz** [comment]
Yes, you can - have a look at the compatibility section in the readme https://github.com/mwz/sonar-scala-docker#compatibility-matrix and expand `Other versions` to find out which version of the image you need to pull.

**Comment by wei-luo-exa** [comment]
**mwizner/sonarqube-scala-plugins:3.4.0-full** image works for us. Is there any documentation you recommend about how the line coverage gets calculated. Thanks again!

**Comment by mwz** [comment]
Hi @wei-luo-exa, the line coverage is calculated by SonarQube's engine. We report to SonarQube the number of hits per each line (which we extract from the scoverage report) and then SonarQube figures out the rest. You can find out more in SonarQube's docs [here](https://docs.sonarqube.org/latest/user-guide/metric-definitions/):

> Line coverage (line_coverage)
> On a given line of code, Line coverage simply answers the following question: Has this line of code been executed during the execution of the unit tests?. It is the density of covered lines by unit tests:
> 
> Line coverage = LC / EL
> where
> 
> LC = covered lines (lines_to_cover - uncovered_lines)
> EL = total number of executable lines (lines_to_cover)

**Comment by mwz** [comment]
FYI, from what it looks like to me, we need to aggregate measures for those custom metrics manually, which didn't use to be the case in the past.

I'll try to fix this soon, so keep an eye on this thread.

**Comment by mwz** [comment]
FYI @wei-luo-exa, I've released a new version of the plugin [v8.3.0](https://github.com/mwz/sonar-scala/releases/tag/v8.3.0), which fixes those custom metrics. I'll publish a new Docker image soon.

**Comment by wei-luo-exa** [comment]
@mwz Thanks, is the docker image available with v8.3.0?
