### ISSUE TITLE
Equivalent of SonarJava's "@Deprecated code should not be used" rule

### ISSUE THREAD

**Issue by h-ngo** [mwz/sonar-scala#83]
Is there an equivalent of SonarJava's ""deprecated code should not be used"?

We want it to show up in sonar as a violation, so developers will notice it. However, we can't seem to find a similar rule both in Scalastyle and Scapegoat.

Posted the same question to Scalastyle github, but it seems pretty inactive.

**Comment by mwz** [comment]
Hi @h-ngo, unfortunately, I haven't seen any rules related to detecting the use of deprecated code, except for the [`DeprecatedJavaChecker`](http://www.scalastyle.org/rules-1.0.0.html#org_scalastyle_scalariform_DeprecatedJavaChecker), which flags it up as a warning when you use the `java.lang.Deprecated` annotation yourself, but I don't think that there is one for Scala's `@deprecated` annotation.

I agree that it would be really useful to be able to see all the deprecation warnings from scalac in Sonar, but I'm not aware of either Scalastyle or Scapegoat supporting this. I have a feeling that since Scapegoat is a compier plugin it might be possible to achieve it there, so it's definitely worth asking the question on their project.

**Comment by h-ngo** [comment]
Thank you for quick reply.

We use gradle instead of sbt. Scapegoat's integration with gradle is an open issue, and this plugin requires Scapegoat to be set up in the projects to generate the xml report. Looks like Scapegoat may not be the way to go. At least not in near future.

Wonder if you are aware of anyway to make Sonar to pick up deprecation warnings from scalac, and display them as violation/CodeSmells in Sonar.

We are also trying to see if it's possible to create a custom rule in Scalastyle to detect deprecation usage, but it seems Scalastyle is more like a coding style standard/formatter. May not be possible.

It's strange that this is a common rule for Java, but none of Scala static code analyzers has implemented such rule.

**Comment by mwz** [comment]
@h-ngo, are you happy to close this since you raised the issue upstream?
Feel free to update this issue once you find a solution.
