### ISSUE TITLE
The new built-in scapegoat sensor cannot work.

### ISSUE THREAD

**Issue by bobotu** [mwz/sonar-scala#92]
I have try to use the `sonar-scala v6.5.0` with `sbt-sonar v1.3.0` in a two module project.   

config is
```scala
lazy val sonarSettings = Seq(
  sonarProperties ++= Map(
    "sonar.modules" -> "m1,m2",
    "sonar.scoverage.reportPath" -> "target/scala-2.11/scoverage-report/scoverage.xml",
    "sonar.scala.scapegoat.reportPath" -> "target/scala-2.11/scapegoat-report/scapegoat.xml",
    "sonar.scala.version" -> "2.11.0"
  )
)

lazy val root =
  (project in file(".") withId "root")
    .aggregate(m1, m2)
    .settings(name := "root")
    .settings(skip in publish := true)
    .settings(sonarSettings)
    .settings(aggregate in sonarScan := false)
```  

sadly, it raise an error in sonarScan
`ERROR: [scapegoat] Aborting the scapegoat sensor execution, cause: an error occurred while reading the scapegoat report file: 'target/scala-2.11/scapegoat-report/scapegoat.xml', the error was: target/scala-2.11/scapegoat-report/scapegoat.xml (No such file or directory).`

Use sonar-scanner from command line result in same error.   

Then I have a try of `v6.4.0` with `sonar-scala-extra v1.3.0` with same config. It works well.

I also tried to set `m1.sonar.scala.scapegoat.reportPath` and `m2.sonar.scala.scapegoat.reportPath` in config but it doesn't work.

**Comment by BalmungSan** [comment]
Hi @bobotu thanks for reporting, I'll give it a look the following week.

@mwz, I just noticed that the SBT multi-module example project, also only contains [scalastyle issues](https://sonar.sonar-scala.com/project/issues?id=example-sbt-multi-module&resolved=false), so probably it is because the scapegoat plugin failed. Do you have the logs of that run?

**Comment by mwz** [comment]
Yes, I've noticed that @BalmungSan, but the [logs](https://circleci.com/gh/mwz/sonar-scala/292) only indicate that the scapegoat reports were loaded successfully for each module, but nothing was saved in Sonar for the multi-module sbt project as opposed to the single-module one, which saved the issues successfully...

**Comment by mwz** [comment]
Hi @BalmungSan, this might or might not be related to the issue reported by @bobotu, but it appears that for multi-module projects the sensor loads the main report for each module since we're not passing a path to the report which is relative to the root of the project, but instead it's relative to the current module, which results in the report from the aggregate module being loaded every time.

**Comment by mwz** [comment]
Hi @bobotu, could you give [6.5.1](https://github.com/mwz/sonar-scala/releases/tag/v6.5.1) a try and see if that fixes your issue?

**Comment by mwz** [comment]
I'm going to close this due to lack of activity - please feel free to reopen it if you're still experiencing this issue with the latest release.
